megatools_exe: bin\megatools.exe
tmp_dir: tmp
game_directory: C:\GOG Games\Warlords Battlecry 3
log_file: logs.log
patch_full: http://pastebin.com/raw/WVFD6vjA
patch_notes: https://docs.google.com/document/d/1vo8uL7X3PiP7Zc3RpNMQCbTXnSXemskfshJ9ZcKo9Ks/edit?usp=sharing
patch_music_2: https://pastebin.com/raw/WTpxrYb5
patch_music_3: https://pastebin.com/raw/UKnzCSYK
patch_pl: https://pastebin.com/raw/sPrW9SUc
patch_en: https://pastebin.com/raw/8WnKA1qM
