megatools_exe: bin\megatools.exe
tmp_dir: tmp
game_directory: C:\GOG Games\Warlords Battlecry 3
log_file: logs.log
repository: https://pastebin.com/raw/AmnsV7jg
patch_notes: https://docs.google.com/document/d/1vo8uL7X3PiP7Zc3RpNMQCbTXnSXemskfshJ9ZcKo9Ks/edit?usp=sharing
